spring.application.name=gerenciadorDeImpostos

spring.datasource.url=jdbc:postgresql://localhost:5432/impostosdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springdoc=DEBUG
logging.level.org.springframework=DEBUG
spring.ai.openai.api-key=YOUR_OPENAI_API_KEY

# Configuração de Segurança
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

